import Script from 'next/script';
import React from 'react'
import Image from 'next/image';

function page() {
  return (
    <div>
    <Script>
   { `alert("welcome to conatact page");`}
    </Script>
    
      Contact page
     <Image className="mx-auto" 
    //  width={700} height={700}
    fill={true}
      src="https://tse4.mm.bing.net/th?id=OIP.gtA7DCMjMQohOnTYH9g_dQHaE7&pid=Api&P=0&h=220" alt='no'  quality={100} />
    </div>
  )
}

export default page

export const metadata = {
  title: "contact",
  description: "Generated by create next app",
};
